"""init

Revision ID: cdada956fa4c
Revises: 7996176e2b49
Create Date: 2019-11-18 16:46:06.873329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdada956fa4c'
down_revision = '7996176e2b49'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pages')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('data', sa.TEXT(), nullable=False),
    sa.Column('creator_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='fk_pages_creator_id_users'),
    sa.PrimaryKeyConstraint('id', name='pk_pages'),
    sa.UniqueConstraint('name', name='uq_pages_name')
    )
    # ### end Alembic commands ###
